# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# permissions:
#   contents: read

jobs:
  test_linux:
    runs-on:
    - ubuntu-latest

    # Determine environment based on event type
    environment: 
        name: ${{ github.event_name == 'release' && github.event.action == 'published' && 'prod' || 'test' }}

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-dev.txt
    - name: Test with pytest
      env:
        AZURE_OPENAI_ENDPOINT: ${{ vars.AZURE_OPENAI_ENDPOINT }}
        AZURE_OPENAI_MODEL: ${{ vars.AZURE_OPENAI_MODEL }}
        # AZURE_OPENAI_KEY: ${{ secrets.AZUREOPENAIKEY }}
        AZURE_OPENAI_EMBEDDING_NAME: ${{ vars.AZURE_OPENAI_EMBEDDING_NAME }}
        # AZURE_SEARCH_SERVICE: ${{ vars.AZURESEARCHSERVICE }}
        # AZURE_SEARCH_INDEX: ${{ vars.AZURESEARCHINDEX }}
        # AZURE_SEARCH_KEY: ${{ secrets.AZURESEARCHKEY }}
        # AZURE_SEARCH_QUERY_TYPE: ${{ vars.AZURESEARCHQUERY }}
      run: |
        export PYTHONPATH=$(pwd)
        coverage run -m pytest -v --show-capture=stdout
        coverage report -m --include=app.py,backend/*,tests/*
        coverage xml