name: Deploy to Azure Web App

on:
  push:
    branches:
      - main
  release:
    types: [published]

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Azure Login
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID_TEST }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID_TEST }}


    - name: Deploy to Azure Web App
      env:
        WEBAPP_NAME: ${{ vars.WEBAPP_NAME_TEST }}
        RESOURCE_GROUP_APP: ${{ vars.RESOURCE_GROUP_APP_TEST }}
        RESOURCE_GROUP_ASP: ${{ vars.RESOURCE_GROUP_ASP_TEST }}
        APP_SERVICE_PLAN: ${{ vars.APP_SERVICE_PLAN_NAME_TEST }}  # Make sure to set this variable
      run: |
        echo "Deploying to Web App $WEBAPP_NAME in Resource Group $RESOURCE_GROUP_APP using App Service Plan in $RESOURCE_GROUP_ASP"
        az webapp create --name $WEBAPP_NAME --resource-group $RESOURCE_GROUP_APP --plan $APP_SERVICE_PLAN --runtime "PYTHON:3.11"
        az webapp config set --name $WEBAPP_NAME --resource-group $RESOURCE_GROUP_APP --startup-file "python3 -m gunicorn app:app"

    - name: Set Web App Environment Variables
      env:
        WEBAPP_NAME: ${{ vars.WEBAPP_NAME_TEST }}
        RESOURCE_GROUP_APP: ${{ vars.RESOURCE_GROUP_APP }}
        AZURE_OPENAI_EMBEDDING_NAME: ${{ vars.AZURE_OPENAI_EMBEDDING_NAME }}
        AZURE_OPENAI_ENDPOINT: ${{ vars.AZURE_OPENAI_ENDPOINT_TEST }}
        AZURE_OPENAI_MODEL: ${{ vars.AZURE_OPENAI_MODEL }}
      run: |
        az webapp config appsettings set --name $WEBAPP_NAME --resource-group $RESOURCE_GROUP_APP --settings \
          AZURE_OPENAI_EMBEDDING_NAME=$AZURE_OPENAI_EMBEDDING_NAME \
          AZURE_OPENAI_ENDPOINT=$AZURE_OPENAI_ENDPOINT \
          AZURE_OPENAI_MODEL=$AZURE_OPENAI_MODEL

    - name: Azure Logout
      run: |
        az logout