name: Deploy to Azure Web App

on:
  push:
    branches:
      - main
  release:
    types: [published]

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Azure Login
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID_TEST }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID_TEST }}

    - name: Deploy to Azure Web App
      run: |
        chmod +x deploy_to_azure.sh
        ./deploy_to_azure.sh \
          ${{ vars.WEBAPP_NAME_TEST }} \
          "${{ vars.LOCATION }}" \
          ${{ vars.RESOURCE_GROUP_TEST }} \
          ${{ vars.SUBSCRIPTION_TEST }} \
          ${{ vars.SERVICE_PLAN_TEST }} \
          ${{ vars.RESOURCE_GROUP_APP }} \
          ${{ vars.AZURE_OPENAI_EMBEDDING_NAME }} \
          ${{ vars.AZURE_OPENAI_ENDPOINT_TEST }} \
          ${{ vars.AZURE_OPENAI_MODEL }}

    - name: Azure Logout
      run: |
        az logout
