name: Deploy to Azure Web App

on:
  push:
    branches:
      - main
  release:
    types: [published]

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy to Azure Web App
        run: |
          az webapp up --runtime "PYTHON:3.11" --sku B1 --name ${{ vars.WEBAPP_NAME }} --resource-group ${{ vars.RESOURCE_GROUP }} --location ${{ vars.LOCATION }} --subscription ${{ vars.SUBSCRIPTION }}
          az webapp config set --startup-file "python3 -m gunicorn app:app" --name ${{ vars.WEBAPP_NAME }} --resource-group ${{ vars.RESOURCE_GROUP }}

    #   - name: Set Web App Environment Variables
    #     env:
    #       WEBAPP_NAME: ${{ vars.WEBAPP_NAME }}
    #       RESOURCE_GROUP: ${{ secrets.RESOURCE_GROUP }}
    #       AZURE_OPENAI_EMBEDDING_NAME: ${{ vars.AZURE_OPENAI_EMBEDDING_NAME }}
    #       AZURE_OPENAI_ENDPOINT: ${{ vars.AZURE_OPENAI_ENDPOINT }}
    #       AZURE_OPENAI_MODEL: ${{ vars.AZURE_OPENAI_MODEL }}
    #     run: |
    #       az webapp config appsettings set --name $WEBAPP_NAME --resource-group $RESOURCE_GROUP --settings \
    #         AZURE_OPENAI_EMBEDDING_NAME=$AZURE_OPENAI_EMBEDDING_NAME \
    #         AZURE_OPENAI_ENDPOINT=$AZURE_OPENAI_ENDPOINT \
    #         AZURE_OPENAI_MODEL=$AZURE_OPENAI_MODEL

      - name: Azure Logout
        run: |
          az logout
