name: Azure Web App Deployment

on:
  push:
    branches:
      - main
  release:
    types: [published]

permissions:
  id-token: write
  contents: read

jobs:
  deploy-to-test:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    environment: test
    steps:
      - uses: actions/checkout@v4
      - name: Azure login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Deploy to Azure Web App
        env:
          RESOURCE_GROUP: ${{ vars.RESOURCE_GROUP }}
          WEBAPP_NAME: ${{ vars.WEBAPP_NAME }}
        run: |
          pwsh .\setenv.ps1 -resourceGroup $RESOURCE_GROUP -webappName $WEBAPP_NAME
          az webapp up --runtime PYTHON:3.11 --sku B1 --name $WEBAPP_NAME --resource-group $RESOURCE_GROUP
          az webapp config set --startup-file "python3 -m gunicorn app:app" --name $WEBAPP_NAME
          
      - name: Azure logout
        run: az logout

#   deploy-to-prod:
#     runs-on: ubuntu-latest
#     if: github.event_name == 'release'
#     environment: prod
#     steps:
#       - uses: actions/checkout@v4
      
#       - name: Azure login
#         uses: azure/login@v1
#         with:
#           client-id: ${{ secrets.AZURE_CLIENT_ID }}
#           tenant-id: ${{ secrets.AZURE_TENANT_ID }}
#           subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          
#       - name: Set up Python
#         uses: actions/setup-python@v4
#         with:
#           python-version: '3.11'
          
#       - name: Install dependencies
#         run: |
#           python -m pip install --upgrade pip
#           pip install -r requirements.txt
          
#       - name: Deploy to Azure Web App
#         env:
#           RESOURCE_GROUP: ${{ vars.RESOURCE_GROUP }}
#           WEBAPP_NAME: ${{ vars.WEBAPP_NAME }}
#         run: |
#           pwsh .\setenv.ps1 -resourceGroup $RESOURCE_GROUP -webappName $WEBAPP_NAME
#           az webapp up --runtime PYTHON:3.11 --sku B1 --name $WEBAPP_NAME --resource-group $RESOURCE_GROUP
#           az webapp config set --startup-file "python3 -m gunicorn app:app" --name $WEBAPP_NAME
          
#       - name: Azure logout
#         run: az logout