name: CI/CD Pipeline

on:
  push:
    branches:
      - main


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v1
        with:
          python-version: '3.11'

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate
      
      - name: Install dependencies
        run: pip install -r requirements.txt
        
      # Optional: Add step to run tests here (PyTest, Django test suites, etc.)

      - name: Zip artifact for deployment
        run: zip release.zip ./* -r

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v3
        with:
          name: python-app
          path: |
            release.zip
            !venv/



  deploy:
    runs-on: ubuntu-latest
    needs: build

    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: unzip release.zip


      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID_TEST }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID_TEST }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        id: deploy-to-webapp
        with:
          app-name: ${{ vars.WEBAPP_NAME_TEST }}
          resource-group-name: ${{ vars.RESOURCE_GROUP_TEST }}
          slot-name: production

      - name: Set App Settings
        env:
          AZURE_OPENAI_MODEL: ${{ vars.AZURE_OPENAI_MODEL }}
        uses: azure/appservice-settings@v1
        with:
          app-name: ${{ vars.WEBAPP_NAME_TEST }}
          app-settings-json: '[
            {
              "name": "DEBUG",
              "value": "True"
            },
            {
              "name": "AZURE_OPENAI_TEMPERATURE",
              "value": "0"
            },
            {
              "name": "AZURE_OPENAI_TOP_P",
              "value": "0"
            },
            {
              "name": "AZURE_OPENAI_MAX_TOKENS",
              "value": "800"
            },
            {
              "name": "AZURE_OPENAI_MODEL",
              "value": "${{ env.AZURE_OPENAI_MODEL }}"
            }
          ]'
            
              

  #,
              # {
              #   "name": "AZURE_OPENAI_KEY",
              #   "value": "${{ env.AZURE_OPENAI_KEY_TEST }}"
              # },
              # {
              #   "name": "AZURE_OPENAI_RESOURCE",
              #   "value": "${{ env.AZURE_OPENAI_RESOURCE_TEST }}"
              # },
              # {
              #   "name": "AZURE_OPENAI_MODEL",
              #   "value": "${{ env.AZURE_OPENAI_MODEL }}"
              # },
              # {
              #   "name": "AZURE_OPENAI_SYSTEM_MESSAGE",
              #   "value": "${{ env.AZURE_OPENAI_SYSTEM_MESSAGE }}"
              # },
              # {
              #   "name": "AZURE_OPENAI_ENDPOINT",
              #   "value": "${{ env.AZURE_OPENAI_ENDPOINT_TEST }}"
              # },
              # {
              #   "name": "AZURE_OPENAI_EMBEDDING_NAME",
              #   "value": "${{ env.AZURE_OPENAI_EMBEDDING_NAME }}"
              # },
              # {
              #   "name": "AZURE_OPENAI_EMBEDDING_ENDPOINT",
              #   "value": "${{ env.AZURE_OPENAI_ENDPOINT_TEST }}"
              # },
              # {
              #   "name": "AZURE_OPENAI_EMBEDDING_KEY",
              #   "value": "${{ env.AZURE_OPENAI_KEY_TEST }}"
              # },
              # {
              #   "name": "AZURE_SEARCH_SERVICE",
              #   "value": "${{ env.AZURE_SEARCH_SERVICE_TEST }}"
              # },
              # {
              #   "name": "AZURE_SEARCH_SERVICE_ENDPOINT",
              #   "value": "https://${{ env.AZURE_SEARCH_SERVICE_TEST }}.search.windows.net"
              # },
              # {
              #   "name": "AZURE_SEARCH_INDEX",
              #   "value": "${{ env.AZURE_SEARCH_INDEX }}"
              # },
              # {
              #   "name": "AZURE_SEARCH_KEY",
              #   "value": "${{ env.AZURE_SEARCH_KEY_TEST }}"
              # }