# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - vita-axerweb-com-br

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://acrvita.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_dcc2a4d605094182b0812cd5dc09d216 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_e329efb8ce9e4ff79692adf38a6e20c2 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: acrvita.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_dcc2a4d605094182b0812cd5dc09d216 }}/fruoccopublic.azurecr.io/sample-app-aoai-chatgpt-vita:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'vita-axerweb-com-br'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_7933591a13a54e258e3704b5f916e0dd }}
        images: 'acrvita.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_dcc2a4d605094182b0812cd5dc09d216 }}/fruoccopublic.azurecr.io/sample-app-aoai-chatgpt-vita:${{ github.sha }}'