name: Build Frontend

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    strategy:
      matrix:
        node-version: [14.x, 16.x]  # Use x to get the latest minor version

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: 'frontend/package-lock.json'
    - name: Install dependencies
      run: npm ci
    - name: Build project
      run: npm run build --if-present
      env:
        NODE_OPTIONS: --max_old_space_size=8192
    - name: Run tests
      run: npm test --if-present